// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	PaymentID     uuid.UUID        `json:"payment_id"`
	OrderID       uuid.UUID        `json:"order_id"`
	UserID        uuid.UUID        `json:"user_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Method        string           `json:"method"`
	Status        string           `json:"status"`
	TransactionID string           `json:"transaction_id"`
	CreatedAt     pgtype.TIMESTAMP(0) `json:"created_at"`
	UpdatedAt     pgtype.TIMESTAMP(0) `json:"updated_at"`
}

type Transaction struct {
	TransactionID uuid.UUID        `json:"transaction_id"`
	UserID        uuid.UUID        `json:"user_id"`
	VendorID      uuid.UUID        `json:"vendor_id"`
	OrderID       uuid.UUID        `json:"order_id"`
	Type          string           `json:"type"`
	Amount        pgtype.Numeric   `json:"amount"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.TIMESTAMP(0) `json:"created_at"`
	UpdatedAt     pgtype.TIMESTAMP(0) `json:"updated_at"`
}
